default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pedro-baptista
  password: mypassword123  # If the user has a password
  host: localhost

development:
  <<: *default
  database: pedroapi_development

test:
  <<: *default
  database: pedroapi_test

production:
  <<: *default
  database: pedroapi_production
  username: pedroapi
  password: <%= ENV['PEDROAPI_DATABASE_PASSWORD'] %>
